captcha:
    height: 80
    width: 240
    length: 6
    max_skew: 0.7
    dot_count: 80
email:
    host: smtp.qq.com
    port: 465
    from: 2272776615@qq.com
    nickname: 原神哥
    secret: crutbzcmqgptdjch
    is_ssl: true
es:
    url: http://elasticsearch:9200
    username: ""
    password: ""
    is_console_print: true
gaode:
    enable: true
    key: 473d20d7f3e813c82cbd28979b7a049b
jwt:
    access_token_secret: IcGEfB2w8eKhBEiuVnDr9PGKXcsdgJ8oGUlw2cUvViI=
    refresh_token_secret: CF45WzHCTBxXcy66Oe1pHswHJzzKNV3Lv9bH7hEOKlU=
    access_token_expiry_time: 2h
    refresh_token_expiry_time: 7d
    issuer: go_blog
mysql:
    host: mysql
    port: 3306
    config: charset=utf8mb4&parseTime=True&loc=Local
    db_name: blog_db
    username: root
    password: root
    max_idle_conns: 10
    max_open_conns: 100
    log_mode: info
qiniu:
    zone: z2
    bucket: yudeng
    img_path: http://image.yyyyyd.com.cn/
    access_key: Lj2fd6Jk6Yb39otS4yX_1DjxiNR54TNOi0yu7K-G
    secret_key: X5jBl33CErgivJBUhds2fLax62GFhAiEnvkffeQK
    use_https: false
    use_cdn_domains: true
qq:
    enable: false
    app_id: "000000000"
    app_key: xxxxxxxxxxxxxxxx
    redirect_uri: http://xxx.xxx/xxx
redis:
    address: redis:6379
    password: ""
    db: 0
rabbitmq:
    dial: amqp://guest:guest@rabbitmq:5672/
system:
    host: 0.0.0.0
    port: 8080
    env: release
    router_prefix: api
    use_multipoint: true
    sessions_secret: fZ9Jxfw5Kb2ra-UP6E3X2mG1LpcaV5mRUW-H6E2lwNs=
    oss_type: qiniu
    admin_email: 2272776615@qq.com
    admin_password: 041135sz
upload:
    size: 20
    path: uploads
website:
    logo: https://iili.io/30DJ7sI.jpg
    full_logo: http://sue7mxmf6.hn-bkt.clouddn.com/cff5211b793f64ff6fbda36479c2ffc8-20250417134306.jpeg
    title: yudeng的个人博客
    slogan: 博客标题
    slogan_en: Blog 
    description: 这是我的个人博客
    version: 1.0.0
    created_at: "2025-4-15"
    icp_filing: 湘ICP备2025114244号
    public_security_filing: 公安备案号
    bilibili_url: https://space.bilibili.com/xxx
    gitee_url: https://gitee.com/xxx
    github_url: https://github.com/YuDeng0102
    name: 月影几度凉
    job: 学生
    address: 江苏苏州
    email: 2272776615@qq.com
    qq_image: ""
    wechat_image: ""
zap:
    level: info
    filename: log/go_blog.log
    max_size: 200
    max_backups: 30
    max_age: 5
    is_console_print: true
