version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: blog-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: blog_db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - blog-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 10

  redis:
    image: redis:7.4-alpine
    container_name: blog-redis
    volumes:
      - redis_data:/data
    networks:
      - blog-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 10s
      retries: 10

  elasticsearch:
    image: elasticsearch:8.17.0
    container_name: blog-es
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - blog-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200/_cat/health"]
      interval: 10s
      timeout: 10s
      retries: 10
  rabbitmq:
    image: rabbitmq:4.1.0-alpine  # 官方4.x没有alpine版本，推荐使用3.11.x
    container_name: blog-rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"   # AMQP协议端口
      - "15672:15672" # 管理界面端口
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    networks:
      - blog-network
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "check_port_connectivity"]
      interval: 10s
      timeout: 10s
      retries: 10

  backend:
    image: yudeng2004/blog-backend:1.0
    # build: .
    container_name: blog-backend
    volumes:
       - ./config.yaml:/app/config.yaml
       - ./entrypoint.sh:/app/entrypoint.sh   
    ports:
      - "8080:8080"
    environment:
      - GOMAXPROCS=1           # 限制 Go 使用 1 个核心
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      elasticsearch:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    networks:
      - blog-network  
    deploy:
      resources:
        limits:
          memory: 1.5G        # 限制容器内存
          cpus: '1.5'          # 限制 CPU 使用

volumes:
  mysql_data:
  redis_data:
  es_data:
  rabbitmq_data:

networks:
  blog-network:
    driver: bridge
    name: blog-network
